
export const SET_PICKED_MONTH = 'SET_PICKED_MONTH';
export const SET_PICKED_YEAR = 'SET_PICKED_YEAR';
export const INSERT_TASK = 'INSERT_TASK';
export const STOP_INSERT_TASK_REQUEST = 'STOP_INSERT_TASK_REQUEST';
export const SEND_INSERT_TASK_REQUEST = 'SEND_INSERT_TASK_REQUEST';